### ISSUE TITLE
Add extra markdown headings to TOC

### ISSUE THREAD

**Issue by marcelklehr** [vue-styleguidist/vue-styleguidist#1067]
**The problem**

When adding additional markdown files for documentation, I usually use headings in those files, but the headings don't show up in the Table of Contents.

**Proposed solution**

I propose to add markdown headings to the table of contents.

**Comment by elevatebart** [comment]
Hello @marcelklehr,

That is an amazing idea, it would be very useful I think.

I unfortunately do not have time to work on it right now.
Would you be open to help out?

If you are, you should check the architecture out.

The way the contents of this TOC is made is in the `styleguide-loader`

https://github.com/vue-styleguidist/vue-styleguidist/blob/c03c0cb7e2000735142851f1600952221ce1688a/packages/vue-styleguidist/src/loaders/styleguide-loader.ts#L70-L79

Then it is rendered by react-styleguidist directly here
https://github.com/styleguidist/react-styleguidist/blob/master/src/client/rsg-components/TableOfContents/TableOfContents.tsx

It feels like something that could be accomplished simply since we are already parsing the markdown for examples. We could at the same time parse it for Level 2 headers.

Let me know if you have questions or if you want to come up with a solution.

**Comment by marcelklehr** [comment]
Hey @elevatebart 

Thanks for the pointers. I think I've come up with a nice way to implement this but I'm not willing to invest as large an amount of time as seems required to get a development set up running.
