### ISSUE TITLE
Doc comment is not working when I use Sections

### ISSUE THREAD

**Issue by pratik-bhatt-hulkapps** [vue-styleguidist/vue-styleguidist#1142]
### When I use sections in the config file
```
module.exports = {
    components: 'src/components/**/*.vue',
    sections: [
        {
            name: 'PActionList',
            content: 'src/components/PActionList/PActionList.md',
            component: 'src/components/PActionList/*.vue',
            description: 'src/components/PActionList/*.vue',
        },
        {
            name: 'PAvatar',
            content: 'src/components/PAvatar/PAvatar.md',
            component: 'src/components/PAvatar/*.vue',
        },

    ],
showSidebar: true,
    pagePerSection: true,

};

```
The Doc Comment (ref: http://i.imgur.com/q3Eryyt.png) is not appearing in Doc. and also I need to import component in the MD file (ref http://i.imgur.com/CtnkSSs.png)
* Before using section these things are working as expected but when I try to use Section I causing these problems.

Is there any way to overcome this? Or any other way to open each component onnew page instead of showing them on a single page.

> Please provide some useful update on this.  Waiting for a positive response 👍🏻

**Comment by elevatebart** [comment]
Hello @pratik-bhatt-hulkapps I see that you might have hit a bug.
Thank you for talking the time to report it.

When you say the Doc comment do not appear in Doc I do not understand what you mean. 
Do you mean the description of the props do not appear on the rendering? 
Do you mean the components are not on the same page as the content?
Do you mean that the props table appears but does not have the descriptions?

Regarding what you are trying to do, if you are trying to have one component per page, I will try and write a quick example where each component has its own page. Maybe I will trip on this bug and be able to fix it.

In the meantime, know that sections do not "need" a content and could have only components or only content and no components.

**Comment by elevatebart** [comment]
This looks like a bug in how sections are managed in react-styleguidist

It might be a while util it is fixed since no-one took the time yet to design and write down a true specification.

`sectionDepth` on sections is doing "stuff". I don't really understand what though. It is [documented in react-styleguidist](https://react-styleguidist.js.org/docs/configuration/#pagepersection) but does not clarify it much for me.

**Comment by pratik-bhatt-hulkapps** [comment]
> Hello @pratik-bhatt-hulkapps I see that you might have hit a bug.
> Thank you for talking the time to report it.
> 
> When you say the Doc comment do not appear in Doc I do not understand what you mean.
> Do you mean the description of the props do not appear on the rendering?
> Do you mean the components are not on the same page as the content?
> Do you mean that the props table appears but does not have the descriptions?
> 
> Regarding what you are trying to do, if you are trying to have one component per page, I will try and write a quick example where each component has its own page. Maybe I will trip on this bug and be able to fix it.
> 
> In the meantime, know that sections do not "need" a content and could have only components or only content and no components.

--------------------------------------------------------------------------------------------------------------------------------

By `Doc Comment do not appear in Doc` I mean to say `the description of the props do not appear on the rendering`

Description of prop and slots are not appearing in documentation also table is not there.
I can see only the component name and content of MD file nothing else.

Please provide any update if you have any. 

Thank you in advance!

**Comment by pratik-bhatt-hulkapps** [comment]
> This looks like a bug in how sections are managed in react-styleguidist
> 
> It might be a while util it is fixed since no-one took the time yet to design and write down a true specification.
> 
> `sectionDepth` on sections is doing "stuff". I don't really understand what though. It is [documented in react-styleguidist](https://react-styleguidist.js.org/docs/configuration/#pagepersection) but does not clarify it much for me.

Nothing is happening when I use this option in VUE.

**Comment by elevatebart** [comment]
If I understand correctly, you only see your Markdown file, not the components documentation.
In this case, the page you are viewing is considered independent from the component and should NOT display anything about the component. 

What you are trying to do (having one component per page) I would try this way:

```js
// styleguide.config.js
module.exports = {
	title: 'Component as pages',
	sections: [
		{
			components: 'src/components/**/[A-Z]*.vue'
			// no content
		}
	],
	pagePerSection: true
}
```

https://github.com/vue-styleguidist/vue-styleguidist/tree/docs/component-per-page/examples/pages

Unfortunately there is a bug upstream: 
- If you have only one section, it is no displayed in the sidebar (it's a shortcut taken by rsg to always deal with sections, and never solo components)
- If your only section has a name, it becomes your landing page 
- Once you click on a component, you can't navigate back to it since not in the sidebar
- If you don't give your main section a name, (to avoid having it as a landing page) it breaks navigation and all components are on the same page.

If you have some spare cycles, I invite you to dig into how sections are managed here:

- [Config normalization](https://github.com/styleguidist/react-styleguidist/blob/master/src/scripts/schemas/config.ts#L219-L234) where if there is no section, rsg creates an artificial one with global `components` as the glob.
- [Sections Processing on Server before sending them to the client react rendering](https://github.com/styleguidist/react-styleguidist/blob/master/src/loaders/utils/getSections.ts)
- [Normalization of the above sections on the client before rendering](https://github.com/styleguidist/react-styleguidist/blob/master/src/client/utils/processSections.ts)
- And finally, [building of the structures for the sidebar in a react component](https://github.com/styleguidist/react-styleguidist/blob/master/src/client/rsg-components/TableOfContents/TableOfContents.tsx)
