### ISSUE TITLE
this.$route is undefined

### ISSUE THREAD

**Issue by happysong** [vue-styleguidist/vue-styleguidist#1150]
**Current behavior**

when i use this.$route in my component, i find $route is undefined and i get errors in the browser console:
Cannot read property 'name' of undefined

**To reproduce**
const routeName = this.$route.name

**Expected behavior**
$route is not undefined

**Comment by elevatebart** [comment]
Hello @happysong

Indeed that is true.
And yet, since the component is exposed in isolation, what would you expect this object to contain?

In styleguidist `$route` objects have to be manually abstracted.

We will have to "mock" the router behavior. We add the following code in a new file, let's call it `styleguide/mockRouter.js`.

```js
// styleguide/mockRouter.js

import Vue from 'vue'

Vue.prototype.$route = Vue.prototype.$route || { 
  // mock all the properties you use
  name: "test"
  params: {p1: 'p1content'},
  query: {},
  path: '<styleguide>',
  meta: {},
  hash: '',
  // ...
}

```

Then add this file in the [require](https://vue-styleguidist.github.io/Configuration.html#require) property of your styleguide.config.js. It will then be run before your styleguide, these setting up your route object.

You can mock other objects in this file like `$router`. 
You can also set up a router-link component if you need to [like this recipe in the documentation suggests](https://vue-styleguidist.github.io/docs/Cookbook.html#use-vue-styleguidist-with-components-that-contain-routing)

**Comment by happysong** [comment]
Thank you very much! I will try it 😁



发自我的iPhone


------------------ Original ------------------
From: Barthélémy Ledoux ***@***.***&gt;
Date: Sat,Jun 12,2021 0:28 AM
To: vue-styleguidist/vue-styleguidist ***@***.***&gt;
Cc: happysong ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [vue-styleguidist/vue-styleguidist] this.$route is undefined (#1150)





 
Hello @happysong
 
Indeed that is true.
 And yet, since the component is exposed in isolation, what would you expect this object to contain?
 
In styleguidist $route objects have to be manually abstracted.
 
We will have to "mock" the router behavior. We add the following code in a new file, let's call it styleguide/mockRouter.js.
 // styleguide/mockRouter.js import Vue from 'vue' Vue.prototype.$route = Vue.prototype.$route || {    // mock all the properties you use   name: "test"   params: {p1: 'p1content'},   query: {},   path: '<styleguide&gt;',   meta: {},   hash: '',   // ... }
 
Then add this file in the require property of your styleguide.config.js. It will then be run before your styleguide, these setting up your route object.
 
You can mock other objects in this file like $router.
 You can also set up a router-link component if you need to like this recipe in the documentation suggests
