### ISSUE TITLE
Parse mixins

### ISSUE THREAD

**Issue by engvuchen** [vue-styleguidist/vue-styleguidist#1191]
I was using the vue-docgen-api and ran into a problem: when parsing a file in node_modules, there was a lack of mixins references in the product;

demo: https://codesandbox.io/s/vue-docgen-api-mixin-props-forked-56w51?file=/src/index.js

I found a related answer. Is this a problem because the ability is not covered?

https://github.com/vue-styleguidist/vue-styleguidist/issues/359

![image](https://user-images.githubusercontent.com/31369318/131634139-9703399a-1aa3-40fa-95da-12b0efb741a9.png)

**Comment by engvuchen** [comment]
Is there any news on the subject?

**Comment by elevatebart** [comment]
Hello @engvuchen,

By default, `vue-docgen-api` ignores everything that is not `node_modules`. Indeed, most of the code in this directory is compiled and minified. If you need to describe the parts of the mixin using comments, you will not be able to modify those components.

I say "by default" because there is an option to redefine this behavior: 

[validExtends](https://vue-styleguidist.github.io/Configuration.html#validextends)

You can use it to define what can be used to extend a component.
