### ISSUE TITLE
console.clear() hides critical errors

### ISSUE THREAD

**Issue by patric-eberle** [vue-styleguidist/vue-styleguidist#121]
When viewing the vue-styleguidist, errors are cleared from the console on init. Unfortunately this sometimes hides critical errors during start up. Is there a possibility to disable this feature?

See the following demo branch: https://github.com/valantic/vue-template/tree/demo/vue-styleguidist_console

If you open in Chrome and enable `preserve log` in the log options of the inspector you suddenly see, that there a three errors shown, which are not visible without the `preserve log`.

**Comment by giulianovarriale** [comment]
Hi. I also noticed this behavior.  I tried to find where the console is being cleared. The problem seems to be on https://github.com/vue-styleguidist/vue-styleguidist/blob/ad9555216155cd875af10bd4b90e72d5b3972f2c/src/rsg-components/Preview/Preview.js#L93. They already have fixed it on react-styleguidist, https://github.com/styleguidist/react-styleguidist/commit/d395ce6a253656365805f82a9401e6ef4229fd70.

I made this change locally to test if it would fix the bug. In fact, this solves it, but then I found another bug. The console.clear is never called, because codeRevision value is always 0. So, I'm not sure if we fix it and never clear the console.log, even with hot reloading, or we try to find the reason codeRevision is never updated. I think the only place codeRevision is updated is here https://github.com/vue-styleguidist/vue-styleguidist/blob/master/src/index.js#L40

**Comment by andreasvirkus** [comment]
Simply check `Preserve log` in your browser's developer tools. @patric-eberle

**Comment by patric-eberle** [comment]
@andreasvirkus Yes I'm aware of this solution. But since this makes development itself not very convenient this is not the best solution from my perspective.

**Comment by caprica-Six** [comment]
> Simply check `Preserve log` in your browser's developer tools. @patric-eberle

Here's a solution that works for me:

  Vue.use(VueAxe, {
    config: {
      // ...
      rules: [
        { id: "heading-order", enabled: true },
        { id: "label-title-only", enabled: true }
      ]
    },
      // Enable console.log errors + vue axe
      clearConsoleOnUpdate: false
  });

**Comment by elevatebart** [comment]
Hello @patric-eberle 
I will consider this issue solved given the previous comment,
If you find this issue again please post another issue here.

Thank you again
