### ISSUE TITLE
Encountered two child with the same key

### ISSUE THREAD

**Issue by stephenjason89** [vue-styleguidist/vue-styleguidist#1218]
I have a console error that i don't know how to debug.
If anyone can point me in the right direction, I would really appreciate it.
Please note that everything is working as expected besides that console error.

Thank you

        "vue-styleguidist": "^4.41.1",

![image](https://user-images.githubusercontent.com/3810177/141670739-b3e129fe-1dc5-4822-a972-afe0ce1b9454.png)

**Comment by elevatebart** [comment]
It looks like styleguidist is having a problem at this line

https://github.com/vue-styleguidist/vue-styleguidist/blob/9e9341d281ab779ccf887607d1f3e04cdde82c98/packages/vue-styleguidist/src/client/rsg-components/Arguments/ArgumentsRenderer.tsx#L40-L42

This seems to be because a method has (according to docgen) two arguments named `this`.
If you find that method and could share it's prototype, it will help solve the problem for everyone.

Thank you in advance

**Comment by stephenjason89** [comment]
Issue is still here on 4.44.19
This is the argument that is named this

<img width="1104" alt="image" src="https://user-images.githubusercontent.com/3810177/158568792-0e744685-24e0-4f77-8fda-26cd057ceb13.png">



This is the code on my component

<img width="596" alt="image" src="https://user-images.githubusercontent.com/3810177/158569627-fae3cb23-b376-419e-8497-b0452441cf5e.png">

Removing one fixes the problem but how do i document this properly?
