### ISSUE TITLE
Module build failed: Error: Could not find file:

### ISSUE THREAD

**Issue by ay13** [vue-styleguidist/vue-styleguidist#123]
I get the above error when running styleguidist in a new repo generated with vue-cli.

options i set in vue-cli: typescript support NOT using class based components

link to repo for example and testing.

https://github.com/ay13/vue-cli-ts-styleguidist

**Comment by rafaesc** [comment]
Hi @ay13,

You uses `vue-webpack-loaders` to config the webpack, you need to use the webpack config of your vue ts project, if you run `vue inspect > output.js`, and copy the rules of `output.js` file on `styleguide.config.js`, it works fine.

But I will create a new version to vue-cli 3, vue-styleguidist should get the webpack config automatic, in order to you can run vue-styleguidist with less settings

Regards.

**Comment by rafaesc** [comment]
More alternatives

https://github.com/vue-styleguidist/vue-styleguidist/issues/114#issuecomment-383611759
