### ISSUE TITLE
ReferenceError: Vue is not defined

### ISSUE THREAD

**Issue by Yonina11-code** [vue-styleguidist/vue-styleguidist#1406]
![image](https://user-images.githubusercontent.com/58586634/194745867-d14129d4-8dba-4e00-bc1e-cfa9cd2330e7.png)

**Comment by elevatebart** [comment]
Hello @Yonina11-code,

Thank you for this issue report.
As you may expect, since all tests are passing in this repo, I have not encountered this error.

Would you please share a little bit more about the context you are seeing it?

The best of the best would be a reproduction.

If you cannot, any info helps
- webpack config
- OS
- Node version
- NPM/Yarn/PnPM?
- version of webpack
- version of vue

Thank you in advance
