### ISSUE TITLE
<docs> seems to have an issue with tab indentation

### ISSUE THREAD

**Issue by d-ryabtsev** [vue-styleguidist/vue-styleguidist#1440]
**Current behavior**

When indenting the <docs> section with tabs, documentation content is not rendered (js error in browser console)

**To reproduce**

Follow the steps to set up a basic vue cli project and add vue-styleguidist to it. I have uploaded an example repo https://github.com/d-ryabtsev/hello-world-example

**Expected behavior**

This issue is not present in `4.28.0` (the version that we are using) and we have quite a large component library. Can you please advise whether this is a bug or an intentional breaking change somewhere between the versions. I don't have a particular issue with removing the tabs but that might take a bit of time and we could do with knowing whether it is worth waiting for a fix here.

**Comment by elevatebart** [comment]
Hello @d-ryabtsev 

This issue is a very trip hazard indeed. You are not the first one to trip on it... I did.

Here is a link to the original markdown definition.
https://www.markdownguide.org/basic-syntax/#code-blocks

When you use tabs in a markdown syntax, it Is immediately interpreted as a code block. 
How was it different in 4.28? 
I tried to make a fork of your repo and brought it back to 4.28.0. The build is failing. 
I would love to see a build passing. If you can help me on that I would be happy.

A quick point of architecture here:

Styleguidist uses "remark" to parse & render the docs. The live aspect is brought through a remark plugin that takes code blocks and changes them a little.

https://github.com/vue-styleguidist/vue-styleguidist/blob/dev/packages/vue-styleguidist/src/loaders/examples-loader.ts#L94

calls chunkify from react-styleguidist

https://github.com/styleguidist/react-styleguidist/blob/master/src/loaders/utils/chunkify.ts

If ReMark thinks it is a code block I will process it as such. If it is to be anything else, then I will skip it.

...

It might still be a bug on vue-styleguidist, but my guts says it's a bug fix that turns out to be breaking your docs.
I can do my best to revert it If I can see what this is supposed to render.

Main question though: Why do you need those tabs? Is it a code format thing?

**Comment by d-ryabtsev** [comment]
Hi @elevatebart 

Thank you for getting back to me.

I think it is a bit of a format thing. From what I can see the tabs in the documentation are purely for indentation purposes and nothing else. Thank you for dropping a link to the markdown guide, that is very useful. It makes sense now why this is trying to parse it as code, I think this may indeed be an issue with our docs. Although we have a lot of components I don't really see a great issue with fixing this on our end if our docs go against the markdown guide. I will discuss this with the team, if I don't get back to this thread - then we have decided to get rid of the tabs!

**Comment by elevatebart** [comment]
I thought about it as well. Docgen switched from using the SFC engine from vue2 to using the SFC engine for Vue3 (even when parsing vue2 components). The change you describe might be a consequence of this update.

**Comment by d-ryabtsev** [comment]
We have decided to remove tabs indentation. Thank you for clarification, closing this issue.
