### ISSUE TITLE
how can use vue-docgen-api in vue3 with .tsx

### ISSUE THREAD

**Issue by zzfn** [vue-styleguidist/vue-styleguidist#1644]
```tsx
import { defineComponent } from 'vue';

const Demo = defineComponent({
  props: {
    name: String,
  },
  setup(props, { slots, emit, expose }) {
    return () => <div>demo</div>;
  },
});
export default Demo;

```

it works in props,but emit only name
it dont work on expose and slots ,how can i use

**Comment by elevatebart** [comment]
I have very little time right now to implement new features in vue docgen.

I think you should turn your eyes to vue-component-meta. It uses volar and typescript to parse components instead of the custom parser I made. It also is official vue stuff. So it's good.

https://www.npmjs.com/package/vue-component-meta

**Comment by zzfn** [comment]
thanks

**Comment by yinmingdi** [comment]
Hi, I also saw your comment in the issue of vue-component-meta. It seems that vue-component-meta does not support tsx either. Have you found any solution yet?

@zzfn

**Comment by elevatebart** [comment]
@johnsoncodehk is it true? It was definitely a feature before v2 wasn't it ?

[EDIT] I found this test
https://github.com/vuejs/language-tools/blob/58a820281d4b4a8b2d484a7fa2a2eb73e5eb4daf/packages/component-meta/tests/index.spec.ts#L779-L798

**Comment by zzfn** [comment]
> Hi, I also saw your comment in the issue of vue-component-meta. It seems that vue-component-meta does not support tsx either. Have you found any solution yet?
> 
> @zzfn

no～
