### ISSUE TITLE
Using Vuelidate

### ISSUE THREAD

**Issue by lgomes2m** [vue-styleguidist/vue-styleguidist#170]
I am using vuelidate to do the validations of inputs.

When I run the styleguide I have this error:
Warning: Cannot parse src/pages/Register/PageRegister.vue: TypeError: (0 , _validators.minLength) is not a function

What can I do??

Thanks!

**Comment by elevatebart** [comment]
Hello @lgomes2m, 

It would be incredibly helpful if you could create a repository where the bug is reproductible.
A form component with one field validated with vuelidate should suffice. 

I do not know how vuelidate is used. It would take me way longer than to you to reproduce it.

Thank you in advance,
Bart

**Comment by lgomes2m** [comment]
Hi @elevatebart ,

My friend already find a solution.

When we import the validations rules this way:
`import { required, email, minLength } from 'vuelidate/lib/validators'`

We have the warning I reported.

But, if we import like this:
`import { required, email } from 'vuelidate/lib/validators'
  import minLength           from 'vuelidate/lib/validators/minLength'`

There is no errors, styleguidist works like a charm.
Don't know why, but it works.

Thanks,
Lucas.

**Comment by rafaesc** [comment]
@lgomes2m Yes, Its an issue of vue-docgen-api.

you can get more information here: 
https://github.com/vue-styleguidist/vue-docgen-api/issues/23#js-timeline-progressive-loader
