### ISSUE TITLE
Unknown language: "vue"

### ISSUE THREAD

**Issue by PhmNgocNghia** [vue-styleguidist/vue-styleguidist#200]
I got Unknown language: "vue" (```vue ```)after update lastest vue-styleguidist. Any solution for troubleshooting this problem ?

**Comment by elevatebart** [comment]
Can you share:
- your package json 
- your style guide.config 
- the version of node you are using 
- windows/macOS or Linux 

Thanks

**Comment by elevatebart** [comment]
Well... good news, I reproduce your bug.

**Comment by DanielPe05** [comment]
Any ideas what could this be? Do you have a fix in mind?

**Comment by elevatebart** [comment]
I have trace it back to highlight.js.
The weird part is that it is throwing this same issue on the working example too.
The issue is just covered when launching codemirror over it.

I need to figure out why codemirror does not start.

**Comment by elevatebart** [comment]
It is probably a dependency that updated and made the change. Still need to figure out which one and to repair it.

**Comment by elevatebart** [comment]
I just found out the cause. It's silly. and my fault.
in this commit e41b3d625e81183a10e50e58de5e2f0b55e75d14, I make styleguidist use react example loader which is rigorously the same as vue-styleguidist except... 

Except it uses the chunkify.js from react-styleguidist who prevents the use of vue code in examples.

Solution #1 wait for the fix
Solution #2 force vue-styleguidist to 1.8.4  & vue-docgen-api to the latest.
Solution #3 use jsx instead of vue for your examples.

Sorry guys I'm on it.
