### ISSUE TITLE
Does not load in IE 11 due to syntax error

### ISSUE THREAD

**Issue by pshendry** [vue-styleguidist/vue-styleguidist#251]
[See minimum repro repository](https://github.com/pshendry/vue-styleguidist-ie11bug) (created using `vue create temp` and `vue add styleguidist`).

Run `npm run styleguide`, open the style guide in IE 11, and observe that it fails to load with a syntax error:

![image](https://user-images.githubusercontent.com/1829032/50850628-40057180-132f-11e9-848c-5a7386061cc4.png)

The line described in the console error is this one:

```
"use strict";
eval("\n\nconst generate = __webpack_require__(/*! regjsgen */ \"./node_modules/regjsgen/regjsgen.js\").generate;\nconst parse = __webpack_require__(/*! regjsparser
```

I would guess this some sort of dependency issue, but I'm not sure how to track it down further.

**Comment by elevatebart** [comment]
Thank you for this report. 
I did not think of checking compatibility with IE 11 with the last releases.
You just made me think of a use case fro it:
- What if we want to use vsg to run compatibility tests of components. 

I will look into it.

**Comment by pshendry** [comment]
Thank you! My use case is that it is just so handy to develop using the "Examples" section of the docs, so it saves time if you can do simple cross-browser testing using the docs themselves.

**Comment by elevatebart** [comment]
Hi @pshendry,

The solution I found is a little bit more hands on that I would have liked. The issue you are facing with IE 11 is that babel does not compile any of the files in node_modules. And some modules chose to remain es6 compatible only. `buble`, used by react-styleguidist is one of those modules. 

In order to fix your build you will have to track down those modules used by vsg and include them to your babel-loader config. You will find houw to do it in [this issue](https://github.com/webpack/webpack/issues/2031)

Tell me if it works.

**Comment by elevatebart** [comment]
Hello @pshendry, Evan works on a mac. Therefore all his slashes are normal. yours are backslashes.

I fought all day with webpack today about it. There is an issue in their regular expression that assumes your OS to be a Mac therefore all `buble/dist/whatever` are never compiled... that is unfortunate indeed. 
You can go ahead and creat a PR to vue-cli if you want this fixed fast. I will probably get on it one day.

Bart
