### ISSUE TITLE
Enable serverPort config to accept string

### ISSUE THREAD

**Issue by MacZel** [vue-styleguidist/vue-styleguidist#275]
`process.env` variables are converted to strings. Running vue-styleguidist with serverPort requires parseInt() beforehand.

Taken from [node.js docs](https://nodejs.org/docs/latest-v8.x/api/process.html#process_process_env):
> Assigning a property on `process.env` will implicitly convert the value to a string.

**Comment by elevatebart** [comment]
Hey @MacZel this is a great point, 

Vuestyleguidist uses react-styleguidists parser for config validation but I believe that fixing it should not be too much trouble.

[vue-styleguidist/scripts/schemas/config.js](https://github.com/vue-styleguidist/vue-styleguidist/blob/master/scripts/schemas/config.js) is the file to modify to change the type. 
In order to avoid webpackDevServer from complaining, the value should as well be converted to an integer in [vue-styleguidist/scripts/config.js](https://github.com/vue-styleguidist/vue-styleguidist/blob/master/scripts/config.js)

Would appreciate a PR of course.
If you need help hit me up on discord or in thhe request ;)

**Comment by MacZel** [comment]
Hi @elevatebart,

I did open a PR.
[vue-styleguidist/scripts/schemas/config.js](https://github.com/vue-styleguidist/vue-styleguidist/blob/master/scripts/schemas/config.js) - in schema I did change type to also enable string value
[vue-styleguidist/scripts/config.js](https://github.com/vue-styleguidist/vue-styleguidist/blob/master/scripts/config.js) - parsing to integer is invoked before sanitizing the config

Waiting for you review
