### ISSUE TITLE
Support .jsx components

### ISSUE THREAD

**Issue by maratfakhreev** [vue-styleguidist/vue-styleguidist#292]
Is it possible to use vue-styleguidist with vue `.jsx` components?

Any attempts lead me to this error `Only can parse files .vue`. I've also tried to setup `webpackConfig` section in styleguide.config.js but it didn't help to resolve the issue.

**Comment by elevatebart** [comment]
Hello @maratfakhreev , 

It is a great point, we should support it. We have all the tools. They are just not put together yet.
If you can add an end to end test to [vue-docgen-api](https://github.com/vue-styleguidist/vue-docgen-api), I can help you add jsx & tsx support.

**Comment by elevatebart** [comment]
After a quick test on vue-docgen, it seems to be working like a charm. I believe the problem is in vsg.
@maratfakhreev What error message are you seeing? 
Do you have a repro codesandbox or github repo ?

Thank you in advance.
Bart

**Comment by johnwebbcole** [comment]
I'm running into this issue also.  I have two cases I'd like to be able to use vue-styleguidist.

1. I have a bunch of `*.js` vue components (embedded template or render functions)
2. In addition to the vue and vue *.js components, I have a lot of `scss` styled components.  I'd like to document them with a `*.md` file and have the fence blocks render the styled components.

I can get pretty close on 2 by using `sections` blocks with `content`.  The only issue is that subsections are bold, which looks odd.

It would be ideal to be able to set components to any of `vue`, `js`, or `md` (where the `md` files just render like the content sections).

**Comment by elevatebart** [comment]
I see that. I will try to treat it as a priority. 
If someone is interested in the resolution of this problem, here is where I would look.

In the [processComponents.js](https://github.com/vue-styleguidist/vue-styleguidist/blob/dev/packages/vue-styleguidist/loaders/utils/processComponent.js) file the test should be a little looser since we can now document all kinds of files.

In the [preview component](https://github.com/vue-styleguidist/vue-styleguidist/blob/dev/packages/vue-styleguidist/src/rsg-components/Preview/Preview.js), could contain some of the parsing of the actual component. I believe this should not be necessary but if the first loosing does not work, this is where you should look.

If you build this, make sure to make an example for other too see how it is done. It would as well be incredibly amazing to add it to the [travis.yml](https://github.com/vue-styleguidist/vue-styleguidist/blob/dev/.travis.yml) for it to be tested on every build.

Thank you all.
