### ISSUE TITLE
vue-docgen-api doesn't support mixins which are result of function execution

### ISSUE THREAD

**Issue by steplov** [vue-styleguidist/vue-styleguidist#359]
Hi,
I'm trying to use vue-styleguidist in a project which uses next pattern for mixins

```
// mixin.js
const factory = () => Vue.extend({});
export default factory();

// component.vue
<script>
import Vue from 'vue';
import mixin from './mixin';

export default Vue.extend({
  name: 'example',
  mixins: [
    mixin
  ]
});
</script>
```
All these components will be ignored by vue-docgen-api 
The same issues happens for nested extend like

```
// component.vue
<script>
import Vue from 'vue';

export default Vue.extend().extend({
  name: 'example2',
});
</script>
```

Do you think these cases should be covered as well? And do you have plans to implement this functionality?

Thanks,
Sergey

**Comment by elevatebart** [comment]
Hi @steplov 

The engine behind vue-styleguidist (vue-docgen-api) avoids executing components at all costs. It allows it to be really fast to extract documentation.

It relies on static analysis and static resolution to load the docs. I do not know how I would find the documentation for props that are "Constructed". How would docgen find the definition of props that for instance would be given in a for loop or how to find what definition to add to a prop that name is:

```js
{
  props:{
    /**
     * what will I associate it with ?
     */
    "myProps" + myComponentName(): string
  }
}
```

it is a very interresting puzzle indeed. I do not think it is impossible. I do not have any intention to work on it for the next 6 month. But I would gladly review a PR.

**Comment by elevatebart** [comment]
Hey @steplov, unless you have immediate intention to work on it, I would like to focus on what we can do now.
I want to close this issue as soon as possible so that it does not lead people to think it is going to happen. 
Thank you for your interest in vue-styleguidist

**Comment by kyleoliveiro** [comment]
I'm currently working on a library of UI components and we are using mixins (which are functions that return objects) to facilitate code reuse and minimize duplicate/redundant code throughout our codebase.

The only way I can get vue-docgen to work with this setup is to work around this issue by using "static" mixins (i.e. objects rather than functions returning objects)—but this would introduce a lot of duplication in my codebase, and make our developer workflow much less efficient.

Are there any updates regarding this issue, or would you be able to point me in the right direction if I were to take it on? @elevatebart

**Comment by kyleoliveiro** [comment]
Thanks for reopening the issue. I'll describe my use case below.

I have a mixin named `CustomTagProvider` which I use to provide a `tag` prop to components so users can choose to render their root elements using a custom html tag. I want the default value of `tag` to be able to be varied based on which component this mixin is applied on.

```
export default ({ value = 'div' } = {}) => ({
  props: {
    tag: {
      type: String,
      default: value,
    },
  },
});
```

**Comment by elevatebart** [comment]
Hello @kyleoliveiro,  Hello @steplov,

vue-docgen-api, since version 4.27.0 can extract some information from mixins factories (functions returning a mixin).
- The info extracted has to be static and contained in the return statement of the function. 
- It also works if it is an arrow function and the object returned is a valid component.

Hope this works for you, if not, please feel free to re-open this issue ;-)
