### ISSUE TITLE
slot breaks with slot-scope

### ISSUE THREAD

**Issue by donaldshen** [vue-styleguidist/vue-styleguidist#431]
**Current behavior**
vue-styleguidist@3.11.4
same as #268
```
<comp slot-scope="{whatever}">
  <!-- @slot you will not see this in the guidist -->
  <slot name="foo"></slot>
</comp>
```
**Expected behavior**
For slot-scope to be detected

**Comment by elevatebart** [comment]
The problem: vue-template-compiler does not return all comments as its structure in the two cases that you mentioned is a little odd.

I will have to change the template parser and all handlers to use sax-js which could result in a breaking change, in order to fix the issues you are having. If you want to make it work fast, you can clone this repo and try to make switch the compiler for sax-js. 

Beware!!! you might need to change the way both handlers are working as `sax-js` is already an event based parser. The new architecture should probably not need a traverse function.

I will try to have an answer for you in the next two weeks.

Bart

**Comment by elevatebart** [comment]
To avoid loading multiple libraries, my best bet is to fix the vue template compiler itself. It should return all comments in components.

**Comment by elevatebart** [comment]
It seems that I misread the code and that I actually need to observe scopedSlots just like children to traverse the v-dom. I will fix it soon ;)
