### ISSUE TITLE
StyleGuideRenderer not being replaced

### ISSUE THREAD

**Issue by nelsonpjunior** [vue-styleguidist/vue-styleguidist#451]
**Current behavior**

following the example on [Cookbook - How to change the layout of a style guide?](https://vue-styleguidist.github.io/docs/Cookbook.html#how-to-change-the-layout-of-a-style-guide) and trying to replace the `StyleGuideRenderer` the same is not being replaced.

When trying to replace the  `SectionsRenderer` with the examples on [customised](https://github.com/vue-styleguidist/vue-styleguidist/tree/dev/examples/customised/)
the following message is printed:
`Uncaught ReferenceError: h is not defined`

> the same happen with any custom component that is loaded

> I tried to set up using both `vue-styleguidist` manual setup and also with the `vue-cli-plugin-styleguidist`.

**To reproduce**
- Create a project using `Vue-CLI 3`
- setup `vue-styleguidist`
- follow the example on [Cookbook - How to change the layout of a style guide?](https://vue-styleguidist.github.io/docs/Cookbook.html#how-to-change-the-layout-of-a-style-guide) and trying to replace the `StyleGuideRenderer` the same is not being replaced.

**Expected behavior**
`StyleGuideRenderer` should be replaced by a custom `StyleGuideRenderer` component

**Notes:**
I've found the following block of code on `make-webpack-config.js`, which seems to be replacing the custom `StyleGuideRenderer` entry:

```js
const custComp = [
  'slots/UsageTabButton',
  'ReactComponent/ReactComponent',
  'StyleGuide/StyleGuideRenderer'
]
const customComponents = custComp.reduce(function(acc, comp) {
  acc[comp] = `Vsg${comp}`
  return acc
}, {})
```
> the line number is `185`

When removing `'StyleGuide/StyleGuideRenderer'` entry, the custom `StyleGuideRenderer` seems to be loaded, then the `Uncaught ReferenceError: h is not defined` starts to be printed again.

**Comment by elevatebart** [comment]
Hello @nelsonpjunior,

You ran into a mix of two issues.

The first is a clarification. If you are going to customize the styleguide, you will have to use react components, they will have to be compiled differently than standard. I created an example to illustrate how you can easily do that.

There was as well an issue with the order I was setting the aliases as. Because of this order Logo and section could be overridden but not the styleguide itself. I fixed this issue in the PR as well.

Tell me if it helps at all.
THank you for reporting,
Bart

**Comment by nelsonpjunior** [comment]
thanks for the support.
