### ISSUE TITLE
`vue-docgen-api` cannot resolve slot attributes when `v-bind` used

### ISSUE THREAD

**Issue by pavelda2** [vue-styleguidist/vue-styleguidist#469]
**Description**

Slot attributes not resolved when using `v-bind` to pass all attributes at once.

**To reproduce**

```
<!-- @slot pass attributes using "v-bind" -->
<slot v-bind="{setFocused, touch, name}"/>
```

**Expected behavior**

Package `vue-docgen-api` generate three bindings:
```
slots: {
  default: {
    bindings: {
      "setFocused": "setFocused",
      "touch": "touch",
      "name": "name"
    }
  }
}
```

**Actual wrong behavior**
Package `vue-docgen-api` generate only one binding:
```
slots: {
  default: {
    bindings: {
      "": "{setFocused, touch, name}"
    }
  }
}
```

**Comment by elevatebart** [comment]
@pavelda2 bad news,

Docgen is a static analysis tool. 
If we do what you desire, we need to do more than parsing, we need to evaluate the code inside of the v-bind. 
Imagine that your keys become calculated like so:

```
<slot v-bind="{ [setFocused + key]:setFocused }"/>
```

or spread like so

```
<slot v-bind="{ ...names }"/>
```

In those cases, I need a clean fallback. Do you think `{'v-bind': '{ ...names }' }` would work ?

In extenso, would it be helpful if instead of an empty string as the key there was `v-bind`?

**Comment by pavelda2** [comment]
You are absolutely right. There are too many syntactic variants of expression inside of `v-bind` tag.

But the empty string as a key is not straightforward. I think the `v-bind` key in `bindings` would be more descriptive.
