### ISSUE TITLE
Can't import mixin as a named import (declared with @) using yarn workspaces and lerna

### ISSUE THREAD

**Issue by bastiW** [vue-styleguidist/vue-styleguidist#478]
**Current behavior**

Import a mixin as a named import is missing first letter after @

All other components are found. 

If we import it like it is described here, then it works:
https://github.com/vue-styleguidist/vue-docgen-api/issues/92#issuecomment-458937553

![image](https://user-images.githubusercontent.com/7667003/60450009-351a0280-9c29-11e9-8b7a-e97f1aad4009.png)

**To reproduce**
We are using yarn workspace together with lernajs. 

**Expected behavior**
should find the mixin

**Comment by bastiW** [comment]
This is our code inside the @cp-fe-platform/mixins index.js file:

``` js
export { default as LocalizedComponent } from './LocalizedComponent.vue';
# ....
```

**Comment by elevatebart** [comment]
Hello @bastiW 
This seems like an issue thank you for reporting.
Can you share the `resolve` part of the webpack config you are using with vue-styleguidist?

**Comment by elevatebart** [comment]
oooooooh got it... lerna's the culprit. I never peek outside the current package. Because you loaded the module with a namespace, it mistook it for some aliased item. I will try to reproduce.

If you can make me a repo for reproduction with the lerna setup I would be very grateful.

**Comment by elevatebart** [comment]
The only place I use substring that could impact our bug here is in [resolveAliases.ts](https://github.com/vue-styleguidist/vue-styleguidist/blob/dev/packages/vue-docgen-api/src/utils/resolveAliases.ts).

Would you please still share the [resolve](https://webpack.js.org/configuration/resolve/) part of your webpackConfig (especially the alias)?

Thank you in advance.
Bart

**Comment by bastiW** [comment]
Hi, 

thanks a lot for your fast response.

this is how our resolve part looks like 

``` js
alias: {
      '@': '/home/cp-dev/cp-fe-platform/packages/viewmodel/src',
      vue$: 'vue/dist/vue.esm.js'
    },
```

(we are working with webpack chain
https://cli.vuejs.org/guide/webpack.html#chaining-advanced) 

Do you still need a repro for debugging?

**Comment by bastiW** [comment]
I set some debugger on the resolveAliases.js

``` js
    const outputPath = path.join(aliases[aliasKeys[i]], filePath.substring(aliasKeys[i].length + 1));
    console.log(aliases)
    console.log("alias: "  + outputPath)
    return outputPath
```

then the output will be 

```js
alias: /home/cp-dev/cp-fe-platform/src/p-fe-platform/mixins
{ '@': '/home/cp-dev/cp-fe-platform/src',
  'vue$': 'vue/dist/vue.esm.js' }
alias: /home/cp-dev/cp-fe-platform/src/p-fe-platform/mixins
Warning: vue-docgen-api cannot parse packages/ui/src/modals/Modal.vue: Error: Neither '/home/cp-dev/cp-fe-platform/src/p-fe-platform/mixins.vue' nor '/home/cp-dev/cp-fe-platform/src/p-fe-platform/mixins.js(x)' or '/home/cp-dev/cp-fe-platform/src/p-fe-platform/mixins/index.js(x)' or '/home/cp-dev/cp-fe-platform/src/p-fe-platform/mixins/index.ts(x)' could be found in '/home/cp-dev/cp-fe-platform/packages/ui/src/modals'


```

The output of the aliases does not seem to be correct here

the value of alias should the same as inside the our packages/mixins folder:

```
 alias: {
      '@': '/home/cp-dev/cp-fe-platform/packages/mixins/src',
      vue$: 'vue/dist/vue.esm.js'
    },
```

**Comment by aspi92** [comment]
Hello @elevatebart ,
I have created the reproduction repository for the issue: [https://github.com/aspi92/vue-styleguidist-478-reproduction](https://github.com/aspi92/vue-styleguidist-478-reproduction)

It seems not to work either with the removed alias (see the commented line in the vue.config.js), but the error message changes when the alias is removed.

Thank you for supporting us!

**Comment by aspi92** [comment]
Hi @elevatebart 
unfortunately, the component with the mixin still does not show up. The @ alias seems to be handled correctly now, but the referenced files are still not found.

I have updated Styleguidist in the reproduction repository in the branch "styleguidist-3-15-3", so that you can reproduce the issue.

Running "yarn styleguidist" produces the following error message:
`Warning: vue-docgen-api cannot parse packages/components/src/ComponentWithMixin.vue: Error: Neither '@issue-reproduction/mixins.vue' nor '@issue-reproduction/mixins.js(x)' or '@issue-reproduction/mixins/index.js(x)' or '@issue-reproduction/mixins/index.ts(x)' could be found in '/home/aspi92/Documents/Repositories/vue-styleguidist-478-reproduction/packages/components/src'
`
Seems that the "@issue-reproduction/mixins" is not looked up in the hoisted node_modules for some reasons.

Could you please take a look again?

**Comment by elevatebart** [comment]
Thank you for following up I will try solving it. 
What you are facing is an issue with docgen. It is not being able to resolve "external" files from another package. The reason is that most of the time, files that are external are in `node_modules`, and those files are compiled, therefore not easily parsed. If I allow for files in node_modules to be parsed docgen will en up failing in almost every project.

Bart

**Comment by aspi92** [comment]
Hi @elevatebart 
Thanks for the reply! I have experimented with the different packages and import types. You can find the results in the `different-imports` branch in the repository.

From my understanding, Docgen has problems to follow external files but just in the case of named imports, which reminds me of [Issue #92](https://github.com/vue-styleguidist/vue-docgen-api/issues/92). The same workaround that worked there also applies in our case. Unfortunately, it would massively impact our code base and, therefore, we struggle to apply it.

Interestingly, everything works fine with a named import of the `validationMixin` mixin from the (vuelidate )[https://github.com/vuelidate/vuelidate] package as shown in the reproduction repository, but does not apply to our own packages, even if we build them. To showcase this, I added the build scripts. After their execution which adds the dist directories with compiled code, the Docgen error message changes from:
`Warning: vue-docgen-api cannot parse packages/components/src/ComponentWithMixin.vue: Error: Neither '@issue-reproduction/mixins.vue' nor '@issue-reproduction/mixins.js(x)' or '@issue-reproduction/mixins/index.js(x)' or '@issue-reproduction/mixins/index.ts(x)' could be found in '/home/aspi92/Documents/Repositories/vue-styleguidist-478-reproduction/packages/components/src'`
to:
`Warning: vue-docgen-api cannot parse packages/components/src/ComponentWithMixin.vue: Error: No suitable component definition found`

**Comment by elevatebart** [comment]
I got one step further, 
Docgen fails in in the `require.resolve("@issue-reproduction/mixins")`.
If you change the `package.json` of mixins from

```
{
  "main": "dist/mixins.umd.js",
  "module": "src/index.js",
}
```

to

```
{
  "name": "@issue-reproduction/mixins",
  "version": "0.0.0",
  "private": true,
  "main": "src/index.js",
  "dependencies": {
    "core-js": "^2.6.5",
    "lerna": "^3.15.0",
    "vue": "^2.6.10"
  }
}
```
it works.

Still investigating why `require.resolve` does not pick up on the `module` field.

**Comment by elevatebart** [comment]
... Bad news, it is in the specs. `require.resolve` resolves the path of modules the `CommonJs` way.
Unless the compiled file `dist/mixins.umd.js` exists, the setup will fail. 

I will do two things : 
- [ ] still build the documentation with what I have and instead of breaking just sending a warning.
- [ ] try using the [`resolve`](https://www.npmjs.com/package/resolve) npm module from browserify to do the resolve even for es6 modules.

in the meantime make sure the setup is compiled before launching styleguidist.

**Comment by bastiW** [comment]
Thanks a lot for fixing
