### ISSUE TITLE
Markdown require() not importing

### ISSUE THREAD

**Issue by andreasvirkus** [vue-styleguidist/vue-styleguidist#49]
Hi!

I've got an issue with a more complex markdown example, where the required data is either not imported or just not seen by Vue (backticks "escaped" just for the example):

```
### Bullet type radio inputs
\```js
const mockedOptions = require('./mocks.js').options;

new Vue({
  template: `
      <bb-radio radioType="bullet"
        :options="opts" 
        name="bullet"></bb-radio>`,
  data() {
    return { opts: mockedOptions }
  },
});
\```
```

And it works fine when I inline the options:

```
### Bullet type radio inputs
\```js
new Vue({
  template: `
    <div>
      <bb-radio radioType="bullet"
        :options="opts"
        name="bullet"></bb-radio>
    </div>`,
  data() {
    return { opts: [
      {
        value: 1,
        text: 'Foo',
      },
      {
        value: 2,
        text: 'Bar',
      },
      {
        value: 30,
        text: 'Foobar',
      },
      {
        value: 45,
        text: 'Foobaz',
      },
    ]}
  },
});
\```
```

**Comment by rafaesc** [comment]
Hi @andreasvirkus,

it's because to parse the file generates a [custom sandbox](https://github.com/vue-styleguidist/vue-docgen-api/blob/master/src/utils/getSandbox.js#L65) for extracting the props, so for the moment it isn't possible, however, you can use [mixins](https://vuejs.org/v2/guide/mixins.html) for add reusables props.

Here explain how you can document mixins
https://github.com/vue-styleguidist/vue-styleguidist/blob/master/docs/Documenting.md#include-mixins

**Comment by rafaesc** [comment]
I don't understand, I need to debug the problem, can you share a repository with the problem?, thanks

**Comment by andreasvirkus** [comment]
Sorry, issue was on my end. I'm using ES6 `export default` in my mocks module and forgot that the structure is different than with `require()`.
