### ISSUE TITLE
Unable to document slots

### ISSUE THREAD

**Issue by patric-eberle** [vue-styleguidist/vue-styleguidist#59]
Using vue-styleguidist@1.3.5 and vue@2.5.2 (webpack)

I'm unable to document the slots. As described in documentation I added the following line to my component, but the slots are not documented in the styleguide:

```html
<template>
  <div class="foo">
    <!-- Use this slot footer -->
    <slot name="footer"></slot>
  </div>
</template>
```

Props, methods and events are working though

**Comment by rafaesc** [comment]
Hi @patric-eberle,

Yes, it happened because you have updated [vue-docgen-api](https://github.com/vue-styleguidist/vue-docgen-api/releases/tag/2.2.0)

I have already  updated vue-styleguidist@1.3.7 with this updating #50 , and the docs
https://github.com/vue-styleguidist/vue-styleguidist/blob/master/docs/Documenting.md#slots-documentation
