### ISSUE TITLE
How can I documenting Vuex state, getters, mutations, and actions?

### ISSUE THREAD

**Issue by faizalami** [vue-styleguidist/vue-styleguidist#612]
How can I documenting Vuex state, getters, mutations, and actions?
I have read the documentation and I found how to documenting components that **using vuex**, but what I need is how to **documenting vuex**.
I also found a tool for documenting vuex, but it using jsdoc [https://www.npmjs.com/package/jsdoc-vuex-plugin](https://www.npmjs.com/package/jsdoc-vuex-plugin).
So, what should I do for documenting vuex, should I combine that jsdoc-vuex-plugin with vue-styleguidist? or are there any other methods?

**Comment by elevatebart** [comment]
Hello @faizalami ,

It is an interresting question you have here. vue-styleguidist is initially meant to document visual components only. You could use it to document more components but this would probably mean a little refactoring on my end. 

The most common use case is, as a library developer, I want to publish a documentation about how to use the components I have created so that developers using my company don't have to reverse engineer my components. 

For this reason, for instance, we chose not to document computed properties, data members and lifetime hooks. They play no role in how you are supposed to use a component.

## solution

Use [vue-docgen-cli](https://www.npmjs.com/package/vue-docgen-cli) to generate markdown files in one folder for the visual components. It relies on the same tools as vue-styleguidist but does not handle rendering. Great for combining it with another tool.
Then use jsdoc-vuex-plugin to generate markdown for vuex state.
Finally, use vuepress or gridsome to render the markdown as a gorgeous website.

Voila !! hope this helps ;-)

**Comment by elevatebart** [comment]
I will close this request, feel free to re-open it if you have more questions
