### ISSUE TITLE
Editor theme is not applied from the config (v4.2.2)

### ISSUE THREAD

**Issue by ol-ko** [vue-styleguidist/vue-styleguidist#682]
Looks like specifying a theme for the editor doesn't work anymore (version 4.2.2 of the vue-styleguidist)
Tried out on the basic example by adding the following to the config:

```
	editorConfig: {
		theme: 'night'
	}
```

Resulting config looks like this (omitted irrelevant parts):

```
// ... all imports left untouched

module.exports = {
	title: 'Vue Styleguidist basic',
	components: 'src/components/**/[A-Z]*.vue',
	defaultExample: true,
	ribbon: {
		text: 'Back to examples',
		url: `${docSiteUrl}/Examples.html`
	},
	version: '1.1.1',
	webpackConfig: {
		// ... webpack config has been left untouched
	},
	usageMode: 'expand',
	exampleMode: 'expand',
	compilerConfig: {
		target: { ie: 11 }
	},
	styleguideDir: 'dist',
	editorConfig: {
		theme: 'night'
	}
}
```

**Comment by elevatebart** [comment]
Hello @ol-ko you are absolutely right and I should add a warning.
In v4 we made prism editors the new default instead of codemirror.
The [simpleEditor](https://vue-styleguidist.github.io/Configuration.html#simpleeditor) parmeter is now on by default.

If you want to customize the colors of the editor, you have to look at the customized example.

So 3 tasks for me
- [ ] Check and update the basic example if necessary
- [ ] Add a little bit of documentation on the option and the styling
- [ ] Display a warning when using editorConfig without specifying `simpleEditor: false`

I hope this helps.

**Comment by ol-ko** [comment]
Thanks for the quick answer @elevatebart !
Is there a support for using different prism themes? Those are waaay prettier 😆

**Comment by elevatebart** [comment]
Unfortunately not yet.
Here is the component building the prism CSS right now.
It is built in our parent library called react-styleguidist:

https://github.com/styleguidist/react-styleguidist/blob/master/src/client/styles/prismTheme.ts

It is building a JSS object usable in the Editor component.
Maybe you could try your hand at a Pull Request

**Comment by elevatebart** [comment]
I believe you can achieve what you want by removing the current styles and using a prism pure CSS theme.
Remove JSS by adding this to the `styles` parameter of your `styleguide.config.js`:

```js
module.exports = {
  // ...
  styles:{
    Editor: {
      root: {
        isolate: true
      }
    }
  }
}
```

and finally adding the prismTheme CSS file to the `require` parameter to load the needed CSS.

Let me know if it works, I suspect JSS to be incredibly annoying if you wish to override it with pure CSS.
