### ISSUE TITLE
Error: require() statements can be added only by editing a Markdown example file

### ISSUE THREAD

**Issue by RyanHavoc** [vue-styleguidist/vue-styleguidist#702]
**Current behavior**

I'm using `vuex` and `vuex-ORM` in my styleguide. I have a parent component that accesses the store internally and passes data to a child component via `v-model`. This works fine as an example. However, I want to show an example for the child component as well so I'm trying to access the store using a `require`. 

The code I'm using in my markdown file is this:

```
const PolicyGroupModel = require('~/store/models/PolicyGroup').default;
const PolicyGroup = PolicyGroupModel.query().with('policies.orgs').find(1);

new Vue({
  data(){
    return {
      PolicyGroup
    }
  },

  template: `
    <PolicyManagerGroup
      :title="PolicyGroup.displayName"
      v-model="PolicyGroup.policies"
      open
    />
  `
})
```

With `js` opening the code block. This results in the following error:

![image](https://user-images.githubusercontent.com/824169/72182178-dbb63b80-33e2-11ea-8542-7406607f5899.png)

However, by chance, I have discovered that if I include a duplicate `require` in a separate code block before this code block like this:

```
const PolicyGroupModel = require('~/store/models/PolicyGroup').default;
<span></span>
```
```
const PolicyGroupModel = require('~/store/models/PolicyGroup').default;
const PolicyGroup = PolicyGroupModel.query().with('policies.orgs').find(1);

new Vue({
  data(){
    return {
      PolicyGroup
    }
  },

  template: `
    <PolicyManagerGroup
      :title="PolicyGroup.displayName"
      v-model="PolicyGroup.policies"
      open
    />
  `
})
```

With `js noeditor` to hide the block my component renders as expected:

![image](https://user-images.githubusercontent.com/824169/72182315-1ddf7d00-33e3-11ea-82b4-6a742709d4d5.png)

I'm using the latest version for `vue-styleguidist`.

**Expected behavior**

I would expect to no have to include a second require in a separate block.

**Comment by elevatebart** [comment]
Hello @RyanHavoc , 

Thanks for the heads up, you found a tricky bug I think.

Is it voluntary for you to import default as a require?
Have you tried import and it does not work?

The issue is definitely in the calulation of pre-imports

https://github.com/vue-styleguidist/vue-styleguidist/blob/85ed33f66c80595d24a36ffa3cd5ccb8b428334c/packages/vue-styleguidist/src/loaders/examples-loader.ts#L91-L95

or in their usage a bit later 

https://github.com/vue-styleguidist/vue-styleguidist/blob/85ed33f66c80595d24a36ffa3cd5ccb8b428334c/packages/vue-styleguidist/src/loaders/examples-loader.ts#L129-L148

I will have a looksie in the week end

**Comment by RyanHavoc** [comment]
Hey @elevatebart ,

That's what's in the documentation: https://vue-styleguidist.github.io/docs/Cookbook.html#how-to-hide-some-components-in-a-style-guide-but-make-them-available-in-examples

If I `import` I get the same require error, though notably, this does render the component:

![image](https://user-images.githubusercontent.com/824169/72203551-edd8be00-3464-11ea-955d-44100ff1609b.png)

Is `import` support in the markdown examples a new thing? When I first started using vue-styleguidist it didn't work at all.

Grateful for any help you can provide with this!

**Comment by elevatebart** [comment]
It is new indeed, it came with vsg 3.6 I believe.

**Comment by elevatebart** [comment]
Hello @RyanHavoc,

I am trying to reproduce the bug you are having with a `~` webpack alias.

I have a `~/datamock.js` file that contains a function returning an array of numbers.

Can you try to modify this example in a fork so that It can reproduce what you see?
Can you tell me if using anything else from the `require("~/anything")` yields the same error?
How do you define the alias for the `~`?

I am on [discord](https://chat.vuejs.org) if you can to talk about it on an IM.

Thank you again

**Comment by elevatebart** [comment]
nevermind I reproduced the bug (setting the full path to the same as yours is making it die)

**Comment by elevatebart** [comment]
in short, the `~` is not guilty

**Comment by elevatebart** [comment]
Found the bug !!! When detecting the format of the story, I completely left out the use of templates in `new Vue({})`

https://github.com/vue-styleguidist/vue-styleguidist/blob/d25b18d9767118f9f8b185e3a59c177b35cdfeda/packages/vue-styleguidist/src/loaders/examples-loader.ts#L77-L91

Because it was going to the case `weird almost jsx of vue-styleguidist`.

The parsed code looking for requires was split in the wrong place, analyzing the code below, and failed silently.

```js
const PolicyGroupModel = require('~/store/models/PolicyGroup').default;
const PolicyGroup = PolicyGroupModel.query().with('policies.orgs').find(1);

new Vue({
  data(){
    return {
      PolicyGroup
    }
  },

  template: `
```

Fix is simple, if in the code I see `new Vue` I simply return the whole code.

**Comment by RyanHavoc** [comment]
@elevatebart I'm sorry to report that this "fix" hasn't resolved my issue. I'm seeing the same behaviour, unfortunately?

**Comment by elevatebart** [comment]
That's a bummer... I was so proud of having found the issue.
Can you try and fork the repo to reproduce your issue in the example?

The problem is in the parsing of the component but might be related to another object.

**Comment by RyanHavoc** [comment]
I can, I'm going to be a bit delayed in trying though. I'm away with work for a week. :-( I will get back to this ASAP though.

**Comment by elevatebart** [comment]
Hello @RyanHavoc 

I created a styleguidist codesandbox. 
Would you mind having a look at reproducing the bug?

<a href="https://codesandbox.io/s/vue-styleguidist-27zvi">
    <img src="https://codesandbox.io/static/img/play-codesandbox.svg" alt="Start documenting"/>
</a>

**Comment by elevatebart** [comment]
Hello @RyanHavoc 

I was wondering if you had time to run through this issue once again?
I really want to help you and for that, I need your help.

Would you please create a reproduction repository?

Thank you in advance,
Bart

**Comment by elevatebart** [comment]
ping @RyanHavoc ?

I would really like to put this bug behind us. 
Tell me if you have time to chat tomorrow.

Bart

**Comment by elevatebart** [comment]
Hey @RyanHavoc I will consider this one closed for now.
Feel free to re-open if needed.
