### ISSUE TITLE
Example file with imports rendering: "Error: require() statements..."

### ISSUE THREAD

**Issue by guillaumeduliscouet** [vue-styleguidist/vue-styleguidist#714]
**Current behavior**
After upgrading `vue-styleguidist` from 4.4.3 to 4.5.0 (the issue is not present in 4.4.3)
Some examples (.vue files imported in .md files) error on render in the styleguide with this message:
```
Error: require() statements can be added only by editing a Markdown example file: require("vuetify/lib")
```
**To reproduce**
Add an `import { VCol } from 'vuetify/lib'` in an external example file 

**Expected behavior**
It should be possible I think. At least it is still working when I force the dependencies to:
```
├─ vue-cli-plugin-styleguidist@4.4.3
│  ├─ vue-styleguidist@^4.4.3
```
The problem is I don't have a clear view on how the code with imports in an external example file is transpiled/resolved/bundled.

I can do some more testing (import not from vuetify, exemple directly in the .md...) if it helps.

**EDIT**: I've reduced it to this 2-files repro (if someone has a styleguidist template for codesandbox I could use it):
````
// readme.md
```vue
  <template>
    <div>
      <div>hello from readme</div>
      <TestImport />
    </div>
  </template>

  <script>
    import TestImport from './TestImport'
    export default {
      components: {
        TestImport,
      }
    }
  </script>
```
````
```
// TestImport.vue
<template>
  <div>hello from import</div>
</template>

<script>
export default {
  name: 'TestImport',
}
</script>
```

**Comment by elevatebart** [comment]
The problem is in [getScript](https://github.com/vue-styleguidist/vue-styleguidist/blob/dev/packages/vue-styleguidist/src/loaders/utils/getScript.ts)

I found the issue, SFC contain `export default`...

So this returns the code instead of the script only 

https://github.com/vue-styleguidist/vue-styleguidist/blob/117e1e0be1556ec77a586a224e4cd890b0452429/packages/vue-styleguidist/src/loaders/utils/getScript.ts#L4-L13

I want this to be a valid example but avoid the heavy parsing of components done in isCodeSFC

```js
import {Comp} from "../Comp"

export default {
  components: "Comp",
  template: `
   <div>Hello</div>
  `
}
```

will fix soon.
