### ISSUE TITLE
npm run styleguide doesn't work for me

### ISSUE THREAD

**Issue by shaci** [vue-styleguidist/vue-styleguidist#790]
I'm using vue-cli 3 and I have installed vue-styleguidist through "vue add styleguidist".
And I get error when go to http://localhost:6060/ (after running "npm run styleguide") -  
'Failed to load resource: the server responded with a status of 404 (Not Found)" for file 
"runtime.bundle.js".
But "npm run styleguide:build" works fine.

**Comment by elevatebart** [comment]
Hello @shaci do you happen to have a repo where I can reproduce?

**Comment by shaci** [comment]
> Hello @shaci do you happen to have a repo where I can reproduce?

Hello, I created the repo. https://github.com/shaci/course-constructor-sample

**Comment by elevatebart** [comment]
in this line, if instead of comparing to development, compare it to production.
https://github.com/shaci/course-constructor-sample/blob/08f2b96fdd3b2fae9d2da62485fad6a7fd79da9d/vue.config.js#L90

like this `.when(process.env.NODE_ENV === "production",` and wow now it does work.
I hope you enjoy the lib.
Why: styleguidist does not load webpack in development mode. But looks for the build process.

**Comment by shaci** [comment]
Thank you!
