### ISSUE TITLE
Documentation for submixes

### ISSUE THREAD

**Issue by pportelaf** [vue-styleguidist/vue-styleguidist#84]
Example:
```jsx
// component.vue
<template>...</template>
<script>
import mixins from '../mixins'
export default {
  name: 'Component'
  mixins: [
    mixins
  ]
}
<script>
```

```jsx
// mixins.js
import parentMixin from '../parentMixin'
/**
 * @mixin
 */
export default {
  mixins: [
    parentMixin
  ],
  props: {
    prop1: {
      type: String,
      default: 'test'
    }
  }
}
```
```jsx
// parentMixin.js
/**
 * @mixin
 */
export default {
  props: {
    prop2: {
      type: String,
      default: 'testing'
    }
  }
}
```

Result:

Prop name | Type | Default | Description
-- | -- | -- | --
prop1 | String | test |  

Expected:

Prop name | Type | Default | Description
-- | -- | -- | --
prop1 | String | test |  
prop2 | String | testing |

**Comment by rafaesc** [comment]
Hi @pportelaf,

this issue is of vue-docgen-api.

It only searches the first object of mixin scripts, it can't add the submixes, it's possible to do a recursivity as solution, however maybe that could bring control problems.

But you can fix it with this hack.
you need to import the submixes in the component without add to the array, like this example

```vue
// component.vue
<template>...</template>
<script>
import mixins from '../mixins'
import parentMixin from '../parentMixin'

export default {
  name: 'Component'
  mixins: [
    mixins
  ]
}
<script>
```

Regards

**Comment by pportelaf** [comment]
Thank you @rafaesc
