### ISSUE TITLE
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by mesqueeb** [vue-styleguidist/vue-styleguidist#847]
**Current behavior**

<img width="800" alt="image" src="https://user-images.githubusercontent.com/3253920/80909326-56c0aa80-8d62-11ea-90f9-42ad2e94006c.png">

**To reproduce**

```
git clone https://github.com/mesqueeb/planetar
git checkout vue-docgen-api-parse
cd api-card/ui
npm i
cd dev
npm i && cd ../
npm run dev
```

**Expected behavior**

No error 😄

**Comment by elevatebart** [comment]
Hello @mesqueeb, 

That is interesting. When are you receiving this error? 
vue-docgen-api is never supposed to be used in the browser. Since it is a static analyzer its role is to be dynamic and look at your files as they are.
Statically analyzing a static analyzer is impossible, pun intended.

I you want ot create static assets from docgen it is very possible though. You might just need to create a webpack-loader. Take a look at @pocka's  https://github.com/pocka/vue-docgen-loader/ to see how it can be done. 

I think you are onto something.

**Comment by mesqueeb** [comment]
@elevatebart feel free to close this issue and document that loader you made for this use-case! 😉

**Comment by elevatebart** [comment]
I might even publish the loader as `vue-docgen-simple-loader`

**Comment by mesqueeb** [comment]
I think I want use your hosted version!
Is it already on npm?

**Comment by elevatebart** [comment]
Will be soon !!

**Comment by fernandopasik** [comment]
@elevatebart would it be possible to add documentation on the use of your loader? It doesn't seem to do the same as https://github.com/pocka/vue-docgen-loader/

**Comment by elevatebart** [comment]
@fernandopasik 
It is a great idea. Would you be OK with making a PR?

To answer your question, `vue-simple-docgen-loader` is meant to be used as follows:

```js
const docobject = require('vue-simple-docgen-loader!./component.vue')
console.log(docobject)
```

The code above will print the object generated by vue-docgen-api without modifications. 
You can find the [specifications for this object here](https://vue-styleguidist.github.io/docs/Docgen.html) and a [full example here](https://github.com/vue-styleguidist/vue-styleguidist/tree/dev/packages/vue-docgen-api#full-example)
@pocka 's loader soes some modification to the object to adapt it to the storybook datamodel.
