### ISSUE TITLE
vue-docgen-cli speed with vuepress and a large components library

### ISSUE THREAD

**Issue by R0LA1mRifcF8yAkk** [vue-styleguidist/vue-styleguidist#885]
Hey, we have a library of about 150 components (and growing). We're currently using vue-styleguidist and the build time is impressive for that amount (it's about 40 seconds).

We're migrating to VuePress and everything is perfect, except for the build time. With all components included it's around 5 minutes right now. At this point, it's very irritating to run several times a day.

What is more, the CLI doesn't watch for `.md` changes, only `.vue`.

1. Can the generation of markdown files be sped up somehow?
    - Could a potential solution be to implement a cache of some sort so only the files that have changed would have to be rebuilt?
2. Can the CLI be made to watch for markdown changes as well?

**Comment by elevatebart** [comment]
We are in the process of migrating styleguidist to use vitepress.
The docgen cli has a couple of perf killers:
1. it runs two separate chokidar processes that are super long to build
2. it builds markdown files for no reson since in the end we are expecting HTML anyway

@JessicaSachs has started the project here:

https://github.com/JessicaSachs/vite-styleguidist

It is still in the very early stage but is very promising.
