### ISSUE TITLE
JavaScript production bundle size larger when using <doc> sections

### ISSUE THREAD

**Issue by steveswinbank** [vue-styleguidist/vue-styleguidist#905]
I'm using Vue single-file-components and would ideally like to use the `<doc>` method of documenting my components.

However, the javascript production bundle (e.g. `dist\js\app.d123aa.js`) file is larger when I create a production build of my Vue app (`npm run build:prod`).

Is there a way to remove the `<doc>` sections when creating a production build and therefore keep the bundle size the same as before?

**Comment by elevatebart** [comment]
I need to verify this with @znck, I thought that `docs` tag was removed from production bundles. 
You may need to use a null-loader to eliminate all the results from docs in order to get to this result.

In the example linked below, a custom docs-loader is used. 
 
https://vue-loader.vuejs.org/guide/custom-blocks.html#example

I would replace it with https://webpack.js.org/loaders/null-loader/
