### ISSUE TITLE
Spread props are ignored in component doc

### ISSUE THREAD

**Issue by youngboy** [vue-styleguidist/vue-styleguidist#923]
**Current behavior**

Spread props are ignored in component doc

**To reproduce**

with vue-docgen-api@4.28.0

```bash
> const docGen = require('vue-docgen-api')
undefined
>
> const source = `
... <script>
... const myProps = { variant: { type: String } }
... export default {
...  props: { ...myProps },
... }
... </script>
... `
undefined
> docGen.parseSource(source, 'dummy.vue').then(r => console.log(r))
Promise { <pending> }
> {
  exportName: 'default',
  displayName: 'dummy',
  description: '',
  tags: {},
  props: undefined,
  events: undefined,
  methods: undefined,
  slots: undefined
}
```

and neither assignment like `props: myProps` is working

**Expected behavior**

variant props get documented

**Comment by elevatebart** [comment]
Hello @youngboy,

Thank you for putting the time to report this.
This one is a bit spiky. 

For performance purposes, docgen is a static analysis tool. 
It means that it looks at the code as it is written, to oppose to how it is at runtime. 
All resolving of variables, requiring of files, merging of objects has to be done manually since the code is not executed.

To accomplish this, you would have to
- detect the spread(s)
- resolve the spread variable(s) - If the variable is in another file, you will need to parse this other file and get the data from there
- read the props in them
- attach them to the proper docs

If you are interested I can guide you through a PR.
