### ISSUE TITLE
Cannot read component definition from native ESM module

### ISSUE THREAD

**Issue by jackysee** [vue-styleguidist/vue-styleguidist#940]
This is a followup to #911 
When the component is exported from another module and **processed by a function**, the component definition cannot be read.

`compA.js`
```
export { _ as default } from "./compA-1234";
```

`comp-1234.js`
```
const comp = {
  render(h) {
    return h("div", this.name);
  },
  props: {
    name: { type: String }
  }
};

function someFunction(c) {
  return c;
}

const __comp__ = someFunction(comp);

export { __comp__ as _ };
```

**To reproduce**

Use this repository https://github.com/jackysee/vue-styleguidist-example 
`compA` cannot be listed in the documentation.

**Comment by elevatebart** [comment]
Hello @jackysee ,

Thank you for reporting this use case. This is a very interesting use case. 
Contrary to tools like storybook who focus on the result of the execution of your code, vue-docgen-api, who powers styleguidist, focuses on your code itself. 

It looks for pattern to be recognized. Then it extracts everything it can from those patterns.

In your case, vue-docgen-api found the export statement. 
It resolved the alias `__comp__` to the `someFunction(comp)`.

Then it stopped and did not look for the definition of `someFunction()`. 
If it had found `someFunction()` it would still have failed because `return c` is not a valid return statement of a component.

Two parts are "missing" in the algorithm to make this work:
- Look up the definition of `someFunction()`
- Look up the definition of `c`.

If you export your comp the parsing will work without any changes to `vue-docgen-api`.

`comp-1234.js`

```js
export const comp = {
  render(h) {
    return h("div", this.name);
  },
  props: {
    name: { type: String }
  }
};

function someFunction(c) {
  return c;
}

const __comp__ = someFunction(comp);

export { __comp__ as _ };
```

Tell me if it helps.

**Comment by jackysee** [comment]
The ESM code is generated by roll up build. It will be hard to control how it extracts common files into modules for reuse.

**Comment by jackysee** [comment]
Actually I'm trying make it work on latest storybook (RC), which uses vue-docgen-api

**Comment by elevatebart** [comment]
Ah... aw. I will try.
