### ISSUE TITLE
How to document Vue.js components in vanilla JS files?

### ISSUE THREAD

**Issue by fireofearth** [vue-styleguidist/vue-styleguidist#941]
Hi there,

I've created a components library which was originally based off the [Bootstrap Vue](https://bootstrap-vue.org/) codebase, so most of the components are declared from inside JS files. For exmple the component `<AimContainer />` (or `<aim-container />`) is declared like so.

It's not clear from the user guide how I should document this component and extract the component's name (`aim-container` in this example) since the documented use cases for vsg is for `vue` or `jsx` files. Does vsg deal with components in `js`?

```
// src/components/container.js
import Vue from 'vue';
import { mergeData } from 'vue-functional-data-merge';
import { arrayIncludes } from '../utils/array';
import { WRAPPED_BY_OPTIONS } from '../utils/constants';

export const props = {
    /**
     * Set the alternative HTML tag for the container to use.
     */
    tag: {
        type: String,
        default: 'div'
    },
    /**
     * Make this container a flex container.
     */
    flex: {
        type: [Boolean, String],
        default: false
    },
    /**
     * Choose styling options in CSS by specifying whether this container is:
     * - browser: wrapper that sets the content width and height to that of the browser viewport.
     * - pane: wrapper that wraps the content within an AimPaneMenu
     * - window: wrapper that wraps the content within an AimWindowMenu
     * - layout: none of the above.
     */
    wrappedBy: {
        type: String,
        default: 'layout',
        validator: str => arrayIncludes(WRAPPED_BY_OPTIONS, str)
    },
};

/**
 * Aim Container
 */
export const AimContainer = {
    name: 'AimContainer',
    functional: true,
    props,
    render(h, { props, data, children }) {
        return h(
            props.tag,
            mergeData(data, {
                staticClass: 'container',
                class: {
                    'flex': props.flex === true || props.flex === '',
                    [`wrapped-by-${props.wrappedBy}`]: props.wrappedBy,
                },
            }),
            children
        );
    }
};
```

Many thanks.

**Comment by fireofearth** [comment]
Ok. I've figured out how to make it work. Updating `styleguide.config.js` with the below allows vsg to detect `AimContainer`. 

```
module.exports = {
    components: 'src/components/**/*.js',
};
```

I'm keeping these points for reference:

1. `props` cannot be separated from the `AimContainer` declaration like above, otherwise the props to be documented. I have to use

```
export default {
    name: 'AimContainer',
    functional: true,
    props: { ... },
    ... 
};
```

2. JS has to be a single file component with a default export. The below does not work.

```
export const AimContainer = {
    name: 'AimContainer',
    functional: true,
    props: { ... },
    ... 
};
```

3. You cannot use `Vue.extend()` to create a component definition. Only documenting of object declarations are possible. For example this is not possible to document in vsg.

```
export const AimContainer = Vue.extend({
    name: 'AimContainer',
    functional: true,
    props: { ... },
    ... 
});
```

*edit*: adding something I missed.

**Comment by fireofearth** [comment]
Should I open separate tickets for the above two points?

1. is also mentioned in storybook repo (along with use case), but I don't see any mention of it in this repo
https://github.com/storybookjs/storybook/issues/11774

**Comment by elevatebart** [comment]
Hello @fireofearth,

vue-docgen-api might not do exactly what you need right now.
This library is looking at your code, searching for recognizable patterns. 
Because it is significantly faster, it does not run your code. 
Therefore, it has no idea what a variable can be unless we tell it explicitly to resolve it.

To answer your 3 points.

1. Props as a variable
Props that are not defined in the component but in a variable are not resolved for now.
I have not seen this use case often enough to know if it is a significant use case. 
I hope you can get other users to chime in. 
If it is not significant, you could always create your own handler by studying the architecture of docgen and propose it in a PR. This contribution would be greatly appreciated

2. Multiple components in the same file
When using vue-docgen-api `parse`, only the first component gets extracted. this is why the function `parseMulti` exists.
You can find all the documentation on those 2 functions on the [readme for vue-docgen-api](https://github.com/vue-styleguidist/vue-styleguidist/tree/dev/packages/vue-docgen-api#parse-vs-parsemulti) and [on the website](https://vue-styleguidist.github.io/docs/Docgen.html#api)

3. Use of Vue.extend() for documented components
If you look at the tests of what is considered a component, `Vue.extend` is in there
https://github.com/vue-styleguidist/vue-styleguidist/blob/457eb9cbe453c0ff79ab85f93629956337cd1669/packages/vue-docgen-api/src/utils/__tests__/resolveExportedComponent.ts#L117-L131
There might be bugs and other kinds of issues linked to the use case you are experiencing. 
I would be happy to fix them with you in docgen's code or in yours wherever it makes sense.

I hope it helps a little.

**Comment by fireofearth** [comment]
Thanks! I've refactored my code so that the points 1-2 have been taken care of. I removed my use of `Vue.extend()` too so haven't really checked.
