### ISSUE TITLE
How to use third-party ui library in my component?

### ISSUE THREAD

**Issue by archi-git** [vue-styleguidist/vue-styleguidist#999]
The document styleguidist generated can not render the element-ui components that i use in my own components, how do i do it?

_main.js_
```js
import ElementUI from 'element-ui';
import 'element-ui/lib/theme-chalk/index.css';
```
_my component_
```html
<template>
  <div class="hello">
    <el-button type="primary">default button</el-button>
    <p>Hello world</p>
  </div>
</template>

<docs>
```jsx
<hello-world></hello-world>
```
</docs>
```

_the page_
![image](https://user-images.githubusercontent.com/22209404/96426887-707e7d00-1230-11eb-9cb6-21ef46a753c2.png)
_the doc page_ 
![image](https://user-images.githubusercontent.com/22209404/96426907-78d6b800-1230-11eb-959e-85ad9906fe0a.png)

**Comment by elevatebart** [comment]
Hello @archi-git 

Welcome to styleguidist and thank you for your question.

There is a cookbook in the documentation website that tries to explain this kind of usecases.
[This entry of the cookbook](https://vue-styleguidist.github.io/docs/Cookbook.html#how-to-add-third-party-plugins-to-the-style-guide) gives you 2 different ways to install element-ui in your docs.

## Option 1: Require

Create a `js` file and install the library in there. If you mention it in the [require](https://vue-styleguidist.github.io/Configuration.html#require) member of your config, it will be run before every page of your styleguide, thus installing the needed components.

## Option 2: renderRootJsx 

Still create a js file but instead of installing plugins using Vue.use, export default the root component you would want to render your examples in. if you register this file using the [renderRootJsx](https://vue-styleguidist.github.io/Configuration.html#renderrootjsx) option, the exported object will be merged with your examples in the documentation.

If you can, I would probably go with option 1 to follow the [Rule of least power](https://en.wikipedia.org/wiki/Rule_of_least_power)

**Comment by archi-git** [comment]
i get it , thanks for your answer ! 😀
